# Setup environment for Docker
language: c
services: docker
notifications:
  email: false

before_install:
  # Get docker image from docker hub
  - docker pull $DOCKER_IMG
  # Set permissions for Docker mount
  - sudo chgrp -hR 1000 $TWO_HOST_PATH

script:
  # Run make inside container
  - docker run --privileged -v $TWO_HOST_PATH:/home/user/two --workdir /home/user/two -e QUIET=0 -ti $DOCKER_IMG make $MAKE_TARGET
<<<<<<< HEAD

jobs:
  include:
    - stage: build
      env: MAKE_TARGET=
    - stage: test
      env: MAKE_TARGET=test

after_success:
  # Run code coverage (doesn't work yet)
  - bash <(curl -s https://codecov.io/bash)
=======

after_success:
  # Run code coverage (doesn't work yet)
  - bash <(curl -s https://codecov.io/bash) -a '-o build/tests/objs/'
>>>>>>> http_state

# Environment variables
env:
# Global environment variables, i.e., set for all builds
  global:
    - DOCKER_IMG='niclabs/embeddable'
    - TWO_HOST_PATH=`pwd`
<<<<<<< HEAD
=======
  matrix:
    # Test compilation
    - MAKE_TARGET=
    # Run tests
    - MAKE_TARGET=test
>>>>>>> http_state
