# Setup environment for Docker
language: c
services: docker
notifications:
  email: false
branches:
  only:
    - master
    - develop

before_install:
  # Get docker image from docker hub
  - docker pull $DOCKER_IMG
  # Set permissions for Docker mount
  - sudo chgrp -hR 100 $TWO_HOST_PATH
  # request codecov to detect CI environment to pass through to docker
  - ci_env=`bash <(curl -s https://codecov.io/env)`

jobs:
  include:
    - stage: test
      name: Unit Tests
      script:
        - >
          docker run --privileged -v $TWO_HOST_PATH:/home/user/work
          $ci_env
          -ti $DOCKER_IMG
          bash -c "QUIET=0 make test && bash <(curl -s https://codecov.io/bash)"
    - stage: h2spec
      name: HTTP/2 Conformance Tests
      script:
        - >
          docker run --privileged -v $TWO_HOST_PATH:/home/user/work
          -ti  $DOCKER_IMG
          bash -c "make && (./bin/server 8888 &) && h2spec -p 8888 || /bin/true"

# Environment variables
env:
# Global environment variables, i.e., set for all builds
  global:
    - DOCKER_IMG='niclabs/embeddable'
    - TWO_HOST_PATH=`pwd`
