# Setup environment for Docker
language: c
services: docker
notifications:
  email: false
branches:
  only:
    - master
    - develop

before_install:
  # Get docker image from docker hub
  - docker pull $DOCKER_IMG
  # Set permissions for Docker mount
  - sudo chgrp -hR 100 $TWO_HOST_PATH
  # request codecov to detect CI environment to pass through to docker
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  # run docker image
  - docker run -d --privileged --name embeddable $ci_env -v $TWO_HOST_PATH:/home/user/work $DOCKER_IMG tail -f /dev/null
  - docker ps

jobs:
  include:
    - stage: unit tests
      script: $SH "QUIET=0 make test"  && $SH "bash <(curl -s https://codecov.io/bash)"
    - stage: http/2 conformance testing
      script: $SH "H2SPEC_SKIP=http2/6.9.2/1 make h2spec"

# Environment variables
env:
# Global environment variables, i.e., set for all builds
  global:
    - DOCKER_IMG='niclabs/embeddable:minimal'
    - TWO_HOST_PATH=`pwd`
    - SH='docker exec -t embeddable bash -c'
