# Setup environment for Docker
language: c
services: docker
notifications:
  email: false
branches:
  only:
    - master
    - develop

before_install:
  # Get docker image from docker hub
  - docker pull $DOCKER_IMG
  # Set permissions for Docker mount
  - sudo chgrp -hR 100 $TWO_HOST_PATH
  # request codecov to detect CI environment to pass through to docker
  - ci_env=`bash <(curl -s https://codecov.io/env)`
  # run docker image
  - docker run -d --privileged --name embeddable $ci_env -v $TWO_HOST_PATH:/home/user/work $DOCKER_IMG tail -f /dev/null
  - docker ps

jobs:
  include:
    - stage: test
      script: $SH "QUIET=0 make test && bash <(curl -s https://codecov.io/bash)"
    - &h2spec
      stage: http/2 conformance testing
      script: $SH "make h2spec PORT=8888 SPEC=$SPEC"
      env: SPEC=generic/1
    - <<: *h2spec
      env: SPEC=generic/2/2
    - <<: *h2spec
      env: SPEC=generic/3.1
    - <<: *h2spec
      env: SPEC=generic/3.2/1

      ##HPACK
    - <<: *h2spec
      env: SPEC=hpack/2.3.3/1
    - <<: *h2spec
      env: SPEC=hpack/5.2/1
    - <<: *h2spec
      env: SPEC=hpack/5.2/2
    - <<: *h2spec
      env: SPEC=hpack/6.1/1
    - <<: *h2spec
      env: SPEC=hpack/6.3/1

# Environment variables
env:
# Global environment variables, i.e., set for all builds
  global:
    - DOCKER_IMG='niclabs/embeddable'
    - TWO_HOST_PATH=`pwd`
    - SH='docker exec -t embeddable bash -c'
