#ifndef PROJECT_CONF_H_
#define PROJECT_CONF_H_

// Contiki logs
#define LOG_CONF_LEVEL_IPV6 LOG_LEVEL_NONE

// Application logs
#undef LOG_LEVEL_HTTP2
#define LOG_LEVEL_HTTP2 LOG_LEVEL_DEBUG

#undef LOG_LEVEL_EVENT
#define LOG_LEVEL_EVENT LOG_LEVEL_DEBUG

#undef LOG_LEVEL_FRAME
#define LOG_LEVEL_FRAME LOG_LEVEL_DEBUG


#endif
