QUIET ?= 0

TARGET = two
SOURCES = two.c \
		  client.c \
		  server.c \
		  http.c \
		  http_bridge.c \
		  http2.c \
		  http2utils.c \
		  frames.c \
		  hpack.c \
		  hpack_utils.c \
		  sock.c \
		  utils.c
LDLIBS = -lm

-include ../Makefile.include
