TARGET = two.a
SOURCES = http.c \
          http_bridge.c \
          http2.c \
          http2utils.c \
          frames.c \
          hpack.c \
          hpack_utils.c \
          sock.c \
          cbuf.c \
          utils.c
